# Config file for running https://github.com/wjdp/htmltest
# See https://github.com/wjdp/htmltest/wiki/Using-With-Hugo

DirectoryPath: /home/mic/projects/velociraptor-docs/public/
TestFilesConcurrently: true
OutputDir: /tmp/.htmltest/
CheckExternal: false
CheckInternal: true
CheckScripts: true
CheckMeta: true
EnforceHTTPS: true
IgnoreHTTPS:
- "localhost:1313"
IgnoreURLs:
- "/app/index.html"
- "\\.\\./img/"
- "\\.local"
- "#/host/server"
- "example.com"
- "https://velociraptor"
- "livereload.js"
- "localhost:1313"
- "test\\."
- "velociraptor-docs/edit/"
- "www.googletagmanager.com"
IgnoreDirs:
- "artifact_references"
- "exchange"
IgnoreAltMissing: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
HTTPConcurrencyLimit: 3
DocumentConcurrencyLimit: 1
