StylesPath = .github/vale
MinAlertLevel = suggestion
Vocab = Velociraptor

[formats]
jsx = md
go = md

## -----------------------------------------------------------------
## VELOCIRAPTOR DOCS REPO 
## -----------------------------------------------------------------

# We don't check content that comes from the Velociraptor repo - i.e.
# artifact descriptions & vql reference - because it should rather be
# checked and corrected at the source.
[content/{announcements,blog,dev,docs,downloads,rss,training}/**/*.md]

# This will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO

# ------------------------------------------------------------------

# We shouldn't check the converted markdown for KB articles - only the
# source MD files where fixes can be applied.
[content/knowledge_base/tips/{*[!index].md}]

# This will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO


# ------------------------------------------------------------------

# We shouldn't check the converted markdown for exchange artifacts - only the
# source YAML files where fixes can be applied.
[content/exchange/artifacts/*.{yml,yaml}]

TokenIgnores = ({{.+}})
BlockIgnores = ({{.+}})

View = artifacts

# This will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

SpecialCases.ThisArtifact = NO

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO

