name: MacOS.Applications.Opera.History
description: |
  Read all users Opera history and collect a copy of the History file.

parameters:
  - name: historyGlobs
    default: /Users/*/Library/Application Support/com.operasoftware.Opera/History
  - name: urlSQLQuery
    default: |
      SELECT url as visited_url, title, visit_count,
             typed_count, last_visit_time
      FROM urls
  - name: userRegex
    default: .

reference:
  - https://book.hacktricks.xyz/generic-methodologies-and-resources/basic-forensic-methodology/specific-software-file-type-tricks/browser-artifacts#opera
  
author: https://github.com/x64-julian

precondition: SELECT OS From info() where OS = 'darwin'

sources:
  - query: |
      LET history_files = SELECT
         parse_string_with_regex(regex="/Users/(?P<User>[^/]+)", string=FullPath).User AS User,
         FullPath, Mtime, upload(file=FullPath) AS Upload
      FROM glob(globs=historyGlobs)
    
      SELECT * FROM foreach(row=history_files,
        query={
           SELECT User, FullPath,
              Mtime,
              visited_url,
              title, visit_count, typed_count,
              timestamp(winfiletime=last_visit_time * 10) as last_visit_time
          FROM sqlite(
             file=FullPath,
             query=urlSQLQuery)
          })
