name: Windows.Applications.Tailscale
description: |
  Decodes the configuration file, pulls log files, and uploads any partial file transfers for Tailscale.
  
  ### History 
  
  - 1.0 - Creation
  
reference:
  - https://ogmini.github.io/tags.html#Tailscale

author: ogmini https://ogmini.github.io

parameters:
  - name: tailscaleProgramDataLocation
    default: C:\\ProgramData\\Tailscale\\
    description: ProgramData Folder for Tailscale

precondition: SELECT OS From info() where OS = 'windows'

sources:
  - name: Configuration 
    description: Configuration lines
    query: |
        SELECT
            _key AS Key,
            base64decode(string=_value) AS Decoded_Value
        FROM foreach(
            row={
                SELECT *
                FROM read_file(filenames=tailscaleProgramDataLocation + "server-state.conf")
            },
            query={
                SELECT
                    _key,
                    _value
                FROM items(
                    item=parse_json(data=Data)
                )
            }
        )
  - name: Logs
    description: Log lines
    query: |
        LET files = SELECT OSPath
            FROM glob(globs="Logs\\tailscale-service*.txt", root=tailscaleProgramDataLocation)

        SELECT
            OSPath,
            Line,
            parse_string_with_regex(string=Line, regex='^([0-9]{4}-(?:(?:02)-(?:0[1-9])|(?:[12][0-9])|(?:(?:0[469]|11)-(?:0[1-9]|[12][0-9]|30))|(?:(?:0[13578]|1[02])-(?:0[1-9]|[12][0-9]|3[01]))T(?:[01][0-9]|2[0-3]):?(?:[0-5][0-9]):?(?:[0-5][0-9])(?:\.[0-9]+)?)(?:[zZ]|(?:[+-][01][0-9]|2[0-3]):?(?:[0-5][0-9])?))(?:\s*:\s*)(.+)').g1 AS Timestamp,
            parse_string_with_regex(string=Line, regex='^([0-9]{4}-(?:(?:02)-(?:0[1-9])|(?:[12][0-9])|(?:(?:0[469]|11)-(?:0[1-9]|[12][0-9]|30))|(?:(?:0[13578]|1[02])-(?:0[1-9]|[12][0-9]|3[01]))T(?:[01][0-9]|2[0-3]):?(?:[0-5][0-9]):?(?:[0-5][0-9])(?:\.[0-9]+)?)(?:[zZ]|(?:[+-][01][0-9]|2[0-3]):?(?:[0-5][0-9])?))(?:\s*:\s*)(.+)').g2 AS ParsedLog
        FROM foreach(
            row=files,
            query={
                SELECT
                    OSPath,
                    Line
                FROM parse_lines(filename=OSPath)
            }
        )
  - name: Partial File Transfers
    description: Partial File Transfers to this machine
    query: |
      LET pFiles = SELECT OSPath
               FROM glob(globs="files\\*\\*.partial", root=tailscaleProgramDataLocation)
  
      SELECT *
      FROM foreach(
          row=pFiles,
          query={
              SELECT upload(file=OSPath) as Upload FROM scope()
          }
      )
